`timescale 1ns / 1ps

//Note that this is the primary UART driver, all other modules are derived from this
//This also calls ctrlMotor which is our primary FSM for moving the car
module uart(
    input sysClk, // Connected to 100MHz clock
    input bitIn,
    output lPWM, rPWM, // These will be connected to mosfets (left side and right side).
    output [6:0] seg, // Connected to seven segment display
    output [3:0] an // Seven segment common anodes
    );
    
    logic waiting; //0 means we are recieving data, 1 means we are done and waiting for a start bit.
    logic [7:0] data; //This stores a byte from the bluetooth reciever
    logic bodCk; //This one runs at 9600 and is generated by the baudCLK module
    logic rstBaud; // Simple reset trigger that resets the baud
    logic trigFSM; //This is triggered whenever we recieve a byte from Bluetooth
    logic [6:0] seg1;
    logic [6:0] seg2;//Buffers for the seven segment displays
    //logic lMotor, rMotor; //These two are simple binary state variables that control pwm Generation
    initial begin
        trigFSM = 0;
        waiting = 1;
        data = 8'b00000000;
    end
    
    
    logic [23:0] delayCtr = 0;
    logic rxEnable = 0;

always_ff @(posedge sysClk) begin //We want to delay recieving until about 10 seconds have passed
    if (delayCtr < 24'd10_000_000_000_000) begin // 10 sec at 100 MHz
        delayCtr <= delayCtr + 1;
        rxEnable <= 0;
    end else begin
        rxEnable <= 1;
    end
end

    //Instatiates the reciever module that stores the data that we get
    rxBit reciever(.bodCk(bodCk), .bitIn(bitIn), .rxEnable(rxEnable), .data(data), .trigFSM(trigFSM));
    
    //Instatiates the baud clock which triggers our reciever
    baudClk baudGenerator(.clk(sysClk), .rst(rstBaud), .bodCk(bodCk), .waiting(waiting));
    
    //Controls the motors based on bluetooth signals. Updates on  trigFSM pulse
    ctrlMotor motorControl(.data(data), .trigFSM(trigFSM), .lMotor(lPWM), .rMotor(rPWM));
    
    //rstDriver detects when the start bit of UART is triggered, which starts the reciever
    rstDriver resetOnStartBit(.sysClk(sysClk), .bitIn(bitIn), .waiting(waiting), .rstBaud(rstBaud));
    
    //Runs the seven segment displays with the most recent data we have.
    seven_seg_decoder decodeSeg(.value(data), .seg1(seg1), .seg2(seg2));
    sevenSegDriver driveSeg(.sysClk(sysClk), .seg1(seg1), .seg2(seg2), .an(an), .seg(seg));

    
    
    
endmodule
