#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 17 10:59:07 MDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim baudClk_func_impl -key {Post-Implementation:sim_1:Functional:baudClk} -tclbatch baudClk.tcl -log simulate.log"
xsim baudClk_func_impl -key {Post-Implementation:sim_1:Functional:baudClk} -tclbatch baudClk.tcl -log simulate.log

